spring:
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/finoper
    username: root
    driver-class-name: org.postgresql.Driver
    password: 123
  sql:
    init:
      platform: postgres
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgresSQL10Dialect